<?php require './templates/task/header.phtml'; ?>
    
<div class="container mt-5">
    <h2>Modificacion de actor</h2>
    <form action="modificar_actor" method="POST">
        
        <div class="mb-3">
            <input type="hidden" class="form-control" id="id_actor" name="id_actor" value="<?= $actor->id_actor ?>">
        </div>
        
        <div class="mb-3">
            <label for="nombre_actor" class="form-label">Nombre del actor</label>
            <input type="text" class="form-control" id="nombre_actor" name="nombre_actor" value="<?= $actor->nombre_actor ?>" required>
        </div>
        
        <div class="mb-3">
            <label for="fecha_nacimiento" class="form-label">Fecha de nacimiento</label>
            <input type="date" class="form-control" id="fecha_nacimiento" name="fecha_nacimiento" value="<?= $actor->fecha_nacimiento ?>" required>
        </div>
        
        <div class="mb-3">
            <label for="edad" class="form-label">Edad</label>
            <input type="number" class="form-control" id="edad" name="edad" value="<?= $actor->edad ?>" required>
        </div>
        
        <div class="mb-3">
            <label for="nacionalidad" class="form-label">Nacionalidad</label>
            <input type="text" class="form-control" id="nacionalidad" name="nacionalidad" value="<?= $actor->nacionalidad ?>" required>
        </div>

        <button type="submit" class="btn btn-primary">Modificar</button>
        <a href="actor" class="btn btn-secondary">Cancelar</a>
    </form>
</div>

<?php require_once 'templates/task/footer.phtml'; ?>